workflow:
  rules: # only run for merge requests, tags, manually from web and the default branch
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'web'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - pre-build
  - build
  - test
  - deploy

default:
# All jobs are run a local docker image. It is named the same on Windows and Ubuntu and must exist on the runners.
  image: calibmar:1.0 

include: 
  - local: '/.gitlab-ci/build-ubuntu.yaml'
  - local: '/.gitlab-ci/build-windows.yaml'